[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pzl"
version = "0.0.1"
dependencies = [
  "psutil >= 5.9",
  "tabulate ~= 0.9",
  "rich ~= 13.5",
]

[project.scripts]
pzl = "pzl:main"
pq = "pzl.pquery:main"
